import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp,readFile,rm,writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { EVENTSPY_COVERAGE } from "../src/lib/tickets/eventspy-coverage.mjs";
import { parseEventSpyTooltipText,buildMarketObservation } from "../src/lib/tickets/market-observation.mjs";
import { eventSpyPacificDate,reserveEventSpyAttempt } from "../scripts/tickets/eventspy-ledger.mjs";
import { eventSpyHistoryCurrent,mergeEventSpyHistory,publishEventSpyHistory,readEventSpyHistory } from "../scripts/tickets/eventspy-history.mjs";
import { browserExtractBatch,collectorExitCode,extractLatestTooltip,runEventSpyCollector,validateUserAgent } from "../scripts/tickets/eventspy-collector.mjs";
const tooltip=await readFile(new URL("../scripts/tickets/fixtures/eventspy-tooltip.txt",import.meta.url),"utf8"),now=Date.parse("2026-08-31T02:01:00Z"),point=parseEventSpyTooltipText(tooltip,{now});
const config=root=>({enabled:true,root,userAgent:"EventSpy offline test",coverage:EVENTSPY_COVERAGE,maxAttempts:2,navigationsPerGame:1});
test("ledger is two per game, independent, atomic under concurrency, and failures remain consumed",async()=>{const root=await mkdtemp(join(tmpdir(),"es-ledger-"));try{const a=EVENTSPY_COVERAGE[0].gameId,b=EVENTSPY_COVERAGE[1].gameId,results=await Promise.all([1,2,3,4].map(()=>reserveEventSpyAttempt(root,a,now)));assert.equal(results.filter(x=>x.allowed).length,2);assert.equal(results.at(-1).allowed,false);assert.equal((await reserveEventSpyAttempt(root,b,now)).allowed,true)}finally{await rm(root,{recursive:true,force:true})}});
test("Pacific midnight and DST are not UTC dates",()=>{assert.notEqual(eventSpyPacificDate(Date.parse("2026-03-08T07:59:00Z")),eventSpyPacificDate(Date.parse("2026-03-08T08:01:00Z")));assert.notEqual(eventSpyPacificDate(Date.parse("2026-11-01T06:59:00Z")),eventSpyPacificDate(Date.parse("2026-11-01T08:01:00Z")))});
test("malformed and future per-game ledger fails closed without blocking another game",async()=>{const root=await mkdtemp(join(tmpdir(),"es-bad-"));try{const a=EVENTSPY_COVERAGE[0].gameId,b=EVENTSPY_COVERAGE[1].gameId;await writeFile(join(root,"bad"),"");await reserveEventSpyAttempt(root,a,now);await writeFile(join(root,"games",a,"attempt-ledger.json"),'{"schemaVersion":2,"gameId":"x","days":[]}\n');await assert.rejects(reserveEventSpyAttempt(root,a,now),{code:"EVENTSPY_LEDGER_INVALID"});assert.equal((await reserveEventSpyAttempt(root,b,now)).allowed,true)}finally{await rm(root,{recursive:true,force:true})}});
test("same source timestamp remains two morning/evening samples while same attempt is idempotent",()=>{const mapping=EVENTSPY_COVERAGE[0],a=buildMarketObservation(point,{mapping,collectedAt:new Date(now).toISOString(),attemptId:"day:1",now}),later=now+12*3600_000,b=buildMarketObservation(point,{mapping,collectedAt:new Date(later).toISOString(),attemptId:"day:2",now:later});let h=mergeEventSpyHistory(null,a,now);h=mergeEventSpyHistory(h,b,later);assert.equal(h.observations.length,2);h=mergeEventSpyHistory(h,b,later);assert.equal(h.observations.length,2)});
test("per-game immutable publication is isolated and failure preserves prior",async()=>{const root=await mkdtemp(join(tmpdir(),"es-history-")),mapping=EVENTSPY_COVERAGE[0],observation=buildMarketObservation(point,{mapping,collectedAt:new Date(now).toISOString(),attemptId:"day:1",now}),current=eventSpyHistoryCurrent(root,mapping.gameId);try{await publishEventSpyHistory(current,observation,{now,mapping});assert.equal((await readEventSpyHistory(current,{now,mapping})).observations.length,1);await assert.rejects(publishEventSpyHistory(current,{...observation,attemptId:"day:2",sampleId:"a".repeat(32),collectedAt:new Date(now+1000).toISOString()},{now:now+1000,mapping,injectFailure:async step=>{if(step==="validated")throw Error("stop")}}));assert.equal((await readEventSpyHistory(current,{now:now+1000,mapping})).observations.length,1)}finally{await rm(root,{recursive:true,force:true})}});
test("three-game partial batch continues A success, B failure, C success and unavailable never extracts",async()=>{const root=await mkdtemp(join(tmpdir(),"es-batch-")),coverage=[...EVENTSPY_COVERAGE.slice(0,3),EVENTSPY_COVERAGE.at(-1)],order=[];try{const result=await runEventSpyCollector(config(root),{now,coverage,extractOne:async mapping=>{order.push(mapping.gameId);if(mapping===coverage[1])throw Error("fixture failure");return point}});assert.deepEqual(order,coverage.slice(0,3).map(x=>x.gameId));assert.equal(result.counts.succeeded,2);assert.equal(result.counts.failed,1);assert.equal(result.outcome,"EVENTSPY_BATCH_PARTIAL_FAILURE");assert.equal((await readEventSpyHistory(eventSpyHistoryCurrent(root,coverage[2].gameId),{now,mapping:coverage[2]})).observations.length,1)}finally{await rm(root,{recursive:true,force:true})}});
test("disabled collector makes zero extraction calls",async()=>{let calls=0;const result=await runEventSpyCollector({...config("unused"),enabled:false},{extractOne:async()=>{calls++}});assert.equal(result.outcome,"EVENTSPY_COLLECTION_DISABLED");assert.equal(calls,0)});

function fakePage(mapping,{url=mapping.sourceUrl,matchup,date=true}={}){
 let currentUrl=url,tooltipReads=0;const handlers={};
 const empty={filter(){return this},first(){return this},async count(){return 0}};
 const tooltipLocator={first(){return this},async count(){return 1},async innerText(){tooltipReads++;return tooltip}};
 const wrapper={async count(){return 1},locator(selector){assert.equal(selector,".recharts-tooltip-wrapper:visible");return tooltipLocator}};
 const chart={async waitFor(){},async focus(){},async press(key){assert.equal(key,"ArrowRight")},locator(selector){assert.match(selector,/recharts-wrapper/);return wrapper}};
 const historyHeading={first(){return this},async waitFor(){},locator(selector){assert.match(selector,/role='application'/);return chart}};
 const dateLocator={first(){return this},async count(){return date?1:0},async waitFor(){}};
 const page={on(name,fn){handlers[name]=fn},mainFrame(){return {}},async goto(){currentUrl=url},url(){return currentUrl},getByText(value){assert.ok(value instanceof RegExp,"only date metadata may use visible-text lookup");return dateLocator},getByRole(role,options){if(role==="dialog")return empty;if(role!=="heading")throw new Error(`unexpected role ${role}`);if(options?.name)return historyHeading;return{async allInnerTexts(){return[matchup??(mapping.homeAway==="home"?`Seattle Seahawks vs. ${mapping.opponent}`:`${mapping.opponent} v Seattle Seahawks`),"Lowest Ticket Price History"]}}}};
 return{page,get tooltipReads(){return tooltipReads},redirect(to){currentUrl=to;handlers.framenavigated?.({})}};
}

test("live adapter accepts absent visible ID and class-only Recharts tooltip after exact matchup/date/URL identity",async()=>{const mapping=EVENTSPY_COVERAGE[0],fake=fakePage(mapping);const result=await extractLatestTooltip(fake.page,mapping,{now});assert.equal(result.sourcePointAt,point.sourcePointAt);assert.equal(fake.tooltipReads,4)});
test("live adapter rejects wrong matchup, date, and redirect before returning",async()=>{const mapping=EVENTSPY_COVERAGE[0];await assert.rejects(extractLatestTooltip(fakePage(mapping,{matchup:"Seattle Seahawks vs. New York Jets"}).page,mapping,{now}),/matchup/);await assert.rejects(extractLatestTooltip(fakePage(mapping,{date:false}).page,mapping,{now}),/date/);await assert.rejects(extractLatestTooltip(fakePage(mapping,{url:`${mapping.sourceUrl}?redirected=1`}).page,mapping,{now}),/redirect/)});
test("user agent is bounded, validated, applied, and browser resources always close",async()=>{for(const value of [undefined,"",`bad\nagent`,"x".repeat(513)])assert.throws(()=>validateUserAgent(value),{code:"EVENTSPY_CONFIG_INVALID"});const mapping=EVENTSPY_COVERAGE[0],fake=fakePage(mapping),closed=[];let contextOptions;const context={async newPage(){return fake.page},async close(){closed.push("context")}},browser={async newContext(options){contextOptions=options;return context},async close(){closed.push("browser")}},chromium={async launch(){return browser}};const result=await browserExtractBatch({...config("unused"),now},[{mapping,now}],chromium);assert.equal(result[0].point.sourcePointAt,point.sourcePointAt);assert.equal(contextOptions.userAgent,"EventSpy offline test");assert.deepEqual(closed,["context","browser"])});
test("browser adapter closes page, context, and browser after an identity rejection",async()=>{const mapping=EVENTSPY_COVERAGE[0],fake=fakePage(mapping,{matchup:"wrong"}),closed=[];const context={async newPage(){return{...fake.page,async close(){closed.push("page")}}},async close(){closed.push("context")}},browser={async newContext(){return context},async close(){closed.push("browser")}};const result=await browserExtractBatch(config("unused"),[{mapping,now}],{async launch(){return browser}});assert.equal(result[0].error,"EVENTSPY_IDENTITY_MISMATCH");assert.deepEqual(closed,["page","context","browser"])});
test("complete and partial batches expose the documented systemd-compatible statuses",()=>{assert.equal(collectorExitCode({outcome:"EVENTSPY_BATCH_SUCCESS"}),0);assert.equal(collectorExitCode({outcome:"EVENTSPY_BATCH_PARTIAL_FAILURE"}),2)});
test("deployment contract keeps partial publication, writable lock, home layout, immutable overlays, and no overlay ports",async()=>{const service=await readFile(new URL("../deployment/systemd/sfz-eventspy-collector@.service",import.meta.url),"utf8"),collectorOverlay=await readFile(new URL("../deployment/eventspy-collector/dev.compose.yml",import.meta.url),"utf8"),syncOverlay=await readFile(new URL("../deployment/ticket-sync/eventspy-dev.compose.yml",import.meta.url),"utf8");assert.match(service,/SuccessExitStatus=2/);assert.match(service,/ReadWritePaths=\/run\/lock/);assert.match(service,/ProtectHome=read-only/);assert.match(service,/--file source\/deployment\/eventspy-collector\/dev\.compose\.yml/);for(const overlay of [collectorOverlay,syncOverlay]){assert.doesNotMatch(overlay,/^\s*web:|ports:/m);assert.match(overlay,/\$\{(?:EVENTSPY_COLLECTOR_IMAGE|TICKET_SYNC_IMAGE):\?/)}assert.match(syncOverlay,/EVENTSPY_HISTORY_ROOT: \/srv\/eventspy/)});
test("collector image context contains the canonical rehearsal fixture",async()=>{assert.equal(await readFile(new URL("../scripts/tickets/fixtures/eventspy-tooltip.txt",import.meta.url),"utf8"),tooltip);const dockerfile=await readFile(new URL("../deployment/eventspy-collector/Dockerfile",import.meta.url),"utf8");assert.match(dockerfile,/COPY --chown=1000:1000 scripts\/tickets/)});
test("helper rejects short, malformed, and wrong-family browser images before host inspection",()=>{const helper=new URL("../deployment/prepare-eventspy-dev.sh",import.meta.url);for(const image of ["mcr.microsoft.com/playwright:v1.62.0-noble@sha256:abcd","mcr.microsoft.com/playwright:v1.62.0-jammy@sha256:"+"a".repeat(64),"mcr.microsoft.com/playwright:v1.55.0-noble@sha256:"+"a".repeat(64)])assert.equal(spawnSync("sh",[helper.pathname,"--browser-image",image],{encoding:"utf8"}).status,64)});
test("helper uses parsed Compose output and documents safe absent-file/env behavior",async()=>{const helper=await readFile(new URL("../deployment/prepare-eventspy-dev.sh",import.meta.url),"utf8");assert.match(helper,/v1\\\.62\\\.0-noble@sha256:\[0-9a-f\]\{64\}/);assert.doesNotMatch(helper,/grep -q ['\"]4324:80/);assert.match(helper,/skip absent files/);assert.match(helper,/Never replace a populated env/)});
