import test from "node:test";
import assert from "node:assert/strict";
import {readFile,mkdtemp,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {parseMirrorArgs,parseMirrorTooltip,atomicPublish} from "../scripts/tickets/eventspy-mirror.mjs";
import {MIRROR_SOURCE_URL,safeMirrorProviderUrl,validateEventSpyMirror} from "../src/lib/tickets/eventspy-mirror-schema.mjs";
const fixture=JSON.parse(await readFile(new URL("fixtures/eventspy-mirror-page.json",import.meta.url)));

test("exact Week 1 snapshot validates and allowlist is fixed",()=>{assert.equal(validateEventSpyMirror(fixture,{now:Date.parse("2026-08-31T12:01:00Z")}),fixture);assert.equal(MIRROR_SOURCE_URL,fixture.sourceUrl);for(const key of ["gameId","sourceEventId","sourceUrl"])assert.throws(()=>validateEventSpyMirror({...fixture,[key]:"wrong"},{now:Date.parse("2026-08-31T12:01:00Z")}))});
test("CLI accepts exactly the three contracts and rejects extras",()=>{assert.equal(parseMirrorArgs(["collect","--game","1392216","--output","/srv/eventspy-mirror/public/1392216.json","--ledger-root","/srv/eventspy-ledger"]).command,"collect");assert.equal(parseMirrorArgs(["validate-file","--file","/x.json"]).command,"validate-file");assert.equal(parseMirrorArgs(["verify-page","--url","http://127.0.0.1:4324/tickets/?game=1392216","--snapshot","/x.json","--screenshot","/x.png"]).command,"verify-page");for(const args of [[],["nope"],["collect","--game","1"],["validate-file","--file","a","--file","b"],["verify-page","--url","https://event-spy.com","--snapshot","x","--screenshot","y"]])assert.throws(()=>parseMirrorArgs(args))});
test("tooltip handles gaps and equal prices, rejects duplicate labels",()=>{const p=parseMirrorTooltip("31 AUG 26 - 03:00 PDT\nTicketmaster\n$267.75\nStubHub\n$267.75\nVividSeats\n—\nSeatGeek\n$270.00",{now:Date.parse("2026-09-01T00:00:00Z")});assert.equal(p.ticketmasterCents,26775);assert.equal(p.stubhubCents,26775);assert.equal(p.vividseatsCents,null);assert.throws(()=>parseMirrorTooltip("31 AUG 26 - 03:00 PDT\nSeatGeek\n$1.00\nSeatGeek\n$1.00",{now:Date.parse("2026-09-01T00:00:00Z")}))});
test("provider URLs reject unsafe schemes, credentials, and secret parameters",()=>{for(const url of ["http://example.com","https://u:p@example.com/x","https://example.com/x?access_token=x","not-url"])assert.equal(safeMirrorProviderUrl(url),null)});
test("semantic constraints reject fields, history ordering, coverage and prices",()=>{const now=Date.parse("2026-08-31T12:01:00Z");assert.throws(()=>validateEventSpyMirror({...fixture,extra:true},{now}));assert.throws(()=>validateEventSpyMirror({...fixture,history:[...fixture.history].reverse()},{now}));assert.throws(()=>validateEventSpyMirror({...fixture,history:[fixture.history[0]]},{now}));assert.throws(()=>validateEventSpyMirror({...fixture,summary:{...fixture.summary,currentLowestCents:0}},{now}))});
test("atomic publication replaces only after validation and preserves last good",async()=>{const dir=await mkdtemp(join(tmpdir(),"mirror-test-")),file=join(dir,"1392216.json");await atomicPublish(file,fixture);const good=await readFile(file,"utf8");await assert.rejects(()=>atomicPublish(file,{...fixture,gameId:"bad"}));assert.equal(await readFile(file,"utf8"),good);await writeFile(join(dir,"unrelated"),"ok")});
test("collector source encodes ledger-before-launch, one goto, traversal and cleanup",async()=>{const source=await readFile(new URL("../scripts/tickets/eventspy-mirror.mjs",import.meta.url),"utf8");assert.match(source,/await reserve\([^)]*MIRROR_GAME_ID/);assert.equal((source.match(/page\.goto\(/g)||[]).length,2,"one collector navigation and one verifier navigation");assert.match(source,/i<500&&same<5/);assert.match(source,/ArrowLeft/);assert.match(source,/ArrowRight/);assert.match(source,/mouse\.move/);assert.match(source,/page\?\.close/);assert.match(source,/context\?\.close/);assert.match(source,/browser\?\.close/);assert.doesNotMatch(source,/console\.log\([^\n]*(?:body|html|cookie|storage)/i)});
