import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { reserveEventSpyAttempt, eventSpyPacificDate } from "../scripts/tickets/eventspy-ledger.mjs";
import { mergeEventSpyHistory, publishEventSpyHistory, readEventSpyHistory } from "../scripts/tickets/eventspy-history.mjs";
import { AUTHORIZED_EVENTSPY_URL } from "../src/lib/tickets/market-observation.mjs";
const observation=(observedAt,collectedAt=observedAt,prices=[10000,11000,12000,13000])=>({schemaVersion:"1.0.0",source:"eventspy",sourceUrl:AUTHORIZED_EVENTSPY_URL,gameId:"1392216",collectedAt,currency:"USD",summary:{currentLowestPriceCents:10000,currentLowestSeenAt:observedAt,currentLowestMarketplace:"ticketmaster",sevenDayLowestPriceCents:10000,sevenDayLowestSeenAt:observedAt},seriesPoint:{observedAt,marketplaces:["ticketmaster","stubhub","vividseats","seatgeek"].map((marketplace,i)=>({marketplace,lowestPriceCents:prices[i]}))}});

test("ledger permits two Pacific-day attempts and denies a third",async()=>{const root=await mkdtemp(join(tmpdir(),"eventspy-ledger-"));try{const now=Date.parse("2026-08-31T20:00:00Z");assert.equal((await reserveEventSpyAttempt(root,now)).allowed,true);assert.equal((await reserveEventSpyAttempt(root,now)).allowed,true);assert.deepEqual(await reserveEventSpyAttempt(root,now),{allowed:false,outcome:"EVENTSPY_DAILY_LIMIT",date:"2026-08-31",attempts:2});}finally{await rm(root,{recursive:true})}});
test("Pacific midnight and DST use America/Los_Angeles calendar dates",()=>{assert.notEqual(eventSpyPacificDate(Date.parse("2026-03-08T07:59:00Z")),eventSpyPacificDate(Date.parse("2026-03-08T08:01:00Z")));assert.notEqual(eventSpyPacificDate(Date.parse("2026-11-01T06:59:00Z")),eventSpyPacificDate(Date.parse("2026-11-01T08:01:00Z")));});
test("concurrent reservations cannot exceed two and malformed ledger fails closed",async()=>{const root=await mkdtemp(join(tmpdir(),"eventspy-race-"));try{const results=await Promise.allSettled([1,2,3,4].map(()=>reserveEventSpyAttempt(root,Date.parse("2026-08-31T20:00:00Z"))));assert.ok(results.filter(r=>r.status==="fulfilled"&&r.value.allowed).length<=2);await writeFile(join(root,"attempt-ledger.json"),"{}\n");await assert.rejects(reserveEventSpyAttempt(root,Date.parse("2026-09-01T20:00:00Z")),{code:"EVENTSPY_LEDGER_INVALID"});}finally{await rm(root,{recursive:true})}});
test("history sorts, deduplicates, retains 45 days, and null cannot overwrite same-point data",()=>{const now=Date.parse("2026-08-31T20:00:00Z"),old=observation("2026-07-01T20:00:00Z"),a=observation("2026-08-31T08:00:00Z"),gap=observation(a.seriesPoint.observedAt,"2026-08-31T09:00:00Z",[null,11000,null,13000]);const merged=mergeEventSpyHistory({observations:[old,a]},gap,now);assert.equal(merged.observations.length,1);assert.equal(merged.observations[0].seriesPoint.marketplaces[0].lowestPriceCents,10000);});
test("history publication atomically switches current and failure preserves prior",async()=>{const root=await mkdtemp(join(tmpdir(),"eventspy-history-")),current=join(root,"current"),now=Date.parse("2026-08-31T20:00:00Z");try{await publishEventSpyHistory(current,observation("2026-08-31T19:00:00Z"),{now});assert.equal((await readEventSpyHistory(current,{now})).observations.length,1);await assert.rejects(publishEventSpyHistory(current,observation("2026-08-31T19:30:00Z"),{now,injectFailure:async step=>{if(step==="validated")throw Error("stop")}}));assert.equal((await readEventSpyHistory(current,{now})).observations.length,1);assert.doesNotMatch(await readFile(join(current,"history.json"),"utf8"),/<html|cookie|localStorage/i);}finally{await rm(root,{recursive:true})}});
