import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import {
  DEFAULT_MODEL, PROMPT_VERSION, buildProfilePrompt, enrichRoster, normalizePlayerName,
  requestBody, runPlayerProfileGeneration, semanticInputHash, validateGeneratedProfile,
} from "../src/lib/player-profile-generation.mjs";
import { isCurrentRosterPlayer } from "../src/lib/roster.mjs";

const roster = (players = [{id:"jane-doe",name:"Jane Doe",position:"WR",number:11,status:"Active"}]) => ({players});
const nfl = (extra = {}) => ({season:2026,playerStatsSeason:2025,updatedAt:"one",playerSeasonStats:[],...extra});
const directory = [{id:99,full_name:"Jane Doe",position:"WR",jersey_number:11,college:"Example U"}];
const validOutput = (withStats = false) => ({bio:"Wide receiver Jane Doe is a current Seattle player. She wears No. 11 and attended Example U. The roster lists her among Seattle's wide receivers, with verified biographical information limited to those details.",recap:withStats?{paragraph:"In the 2025 season statistics, Doe recorded 50 receiving yards. The total reflects the season-level data supplied for this profile.",bullets:["50 receiving yards in 2025"]}:null});
function response(output, usage={input_tokens:100,output_tokens:50,input_tokens_details:{cached_tokens:0},output_tokens_details:{reasoning_tokens:5}}) { return {ok:true,json:async()=>({output_text:JSON.stringify(output),usage}),headers:{get:()=>null}}; }
function tempPaths() { const dir=fs.mkdtempSync(path.join(os.tmpdir(),"sfz-profile-")); return {dir,artifactPath:path.join(dir,"profiles.json"),ledgerPath:path.join(dir,"usage.json"),lockPath:path.join(dir,"lock")}; }
async function run({paths=tempPaths(),existingArtifact={profiles:{}},nflData=nfl(),rosterStore=roster(),playerDirectory=directory,fetchImpl=async()=>response(validOutput()),env={OPENAI_API_KEY:"test"},warn=()=>{}}={}) { return {paths,summary:await runPlayerProfileGeneration({rosterStore,nflData,playerDirectory,existingArtifact,...paths,fetchImpl,env,warn,sleep:async()=>{}})}; }

test("default model is gpt-5.4-mini",()=>assert.equal(DEFAULT_MODEL,"gpt-5.4-mini"));
test("request uses low reasoning, low verbosity, strict schema, and bounded output",()=>{const body=requestBody(DEFAULT_MODEL,enrichRoster(roster(),nfl(),directory)[0]);assert.equal(body.reasoning.effort,"low");assert.equal(body.text.verbosity,"low");assert.equal(body.text.format.strict,true);assert.equal(body.max_output_tokens,1200);});
test("slug roster ID receives stats through exact name/provider match",()=>{const p=enrichRoster(roster(),nfl({playerSeasonStats:[{player_id:99,receiving_yards:50}]}),directory)[0];assert.equal(p.canonicalRosterId,"jane-doe");assert.equal(p.providerPlayerId,"99");assert.equal(p.statistics.receiving_yards,50);});
test("name normalization handles apostrophes, suffixes, hyphens, periods, diacritics, and whitespace",()=>{assert.equal(normalizePlayerName("  J.R. O’Tóole-III "),"jr otoole iii");assert.equal(normalizePlayerName("Montorie Foster Jr."),"montorie foster jr");});
test("ambiguous names do not attach facts",()=>{const warnings=[];const p=enrichRoster(roster(),nfl(),[...directory,{...directory[0],id:100}],(m)=>warnings.push(m))[0];assert.equal(p.providerPlayerId,null);assert.equal(p.college,null);assert.equal(warnings.length,1);});
test("active and Reserve/Injured players are current",()=>{const players=roster([{id:"a",status:"Active"},{id:"b",status:"Reserve/Injured"}]).players.filter(isCurrentRosterPlayer);assert.deepEqual(players.map(p=>p.id),["a","b"]);});
test("historical statuses are excluded",()=>assert.equal(isCurrentRosterPlayer({id:"x",status:"Released"}),false));
test("prompt contains actual statistics season",()=>assert.match(JSON.stringify(buildProfilePrompt({...enrichRoster(roster(),nfl(),directory)[0],statistics:{receiving_yards:1}})),/2025 season statistics/));
test("identical semantic input makes zero calls on second run",async()=>{let calls=0;const paths=tempPaths(),fetchImpl=async()=>{calls++;return response(validOutput())};await run({paths,fetchImpl});const existingArtifact=JSON.parse(fs.readFileSync(paths.artifactPath));const second=await run({paths,fetchImpl,existingArtifact});assert.equal(second.summary.requests,0);assert.equal(calls,1);});
test("changed fetch timestamp does not invalidate cache",async()=>{const paths=tempPaths();await run({paths,nflData:nfl({updatedAt:"one"})});const old=JSON.parse(fs.readFileSync(paths.artifactPath));const second=await run({paths,existingArtifact:old,nflData:nfl({updatedAt:"two"})});assert.equal(second.summary.requests,0);});
test("meaningful stat change invalidates only that player",async()=>{const two=roster([{id:"jane-doe",name:"Jane Doe",position:"WR",number:11,status:"Active"},{id:"john-doe",name:"John Doe",position:"WR",number:12,status:"Active"}]),dir=[...directory,{id:100,full_name:"John Doe",position:"WR",jersey_number:12}];const data=nfl({playerSeasonStats:[{player_id:99,receiving_yards:50},{player_id:100,receiving_yards:20}]});const paths=tempPaths();await run({paths,rosterStore:two,playerDirectory:dir,nflData:data,fetchImpl:async()=>response(validOutput(true))});const old=JSON.parse(fs.readFileSync(paths.artifactPath));let calls=0;const changed=nfl({playerSeasonStats:[{player_id:99,receiving_yards:51},{player_id:100,receiving_yards:20}]});const result=await run({paths,rosterStore:two,playerDirectory:dir,nflData:changed,existingArtifact:old,fetchImpl:async()=>{calls++;return response(validOutput(true))}});assert.equal(calls,1);assert.equal(result.summary.current,1);});
test("prompt version change invalidates old profile once",async()=>{const paths=tempPaths();await run({paths});const old=JSON.parse(fs.readFileSync(paths.artifactPath));const changed=await run({paths,existingArtifact:old,env:{OPENAI_API_KEY:"test",PLAYER_PROFILE_PROMPT_VERSION:"next"}});assert.equal(changed.summary.requests,1);const newest=JSON.parse(fs.readFileSync(paths.artifactPath));const again=await run({paths,existingArtifact:newest,env:{OPENAI_API_KEY:"test",PLAYER_PROFILE_PROMPT_VERSION:"next"}});assert.equal(again.summary.requests,0);});
test("monthly budget prevents calls",async()=>{const paths=tempPaths();fs.writeFileSync(paths.ledgerPath,JSON.stringify({months:{[new Date().toISOString().slice(0,7)]:{requests:1,inputTokens:0,cachedInputTokens:0,outputTokens:0,reasoningTokens:0,estimatedCostUsd:20,models:{}}}}));const x=await run({paths});assert.equal(x.summary.requests,0);});
test("per-run budget prevents calls",async()=>{const x=await run({env:{OPENAI_API_KEY:"test",PLAYER_PROFILE_RUN_BUDGET_USD:"0"}});assert.equal(x.summary.requests,0);});
test("active lock prevents duplicate generation",async()=>{const paths=tempPaths();fs.writeFileSync(paths.lockPath,JSON.stringify({createdAt:new Date().toISOString()}));const x=await run({paths});assert.equal(x.summary.lockSkipped,true);assert.equal(x.summary.requests,0);});
test("failed request preserves old profile",async()=>{const paths=tempPaths(),old={profiles:{"jane-doe":{bio:"Last known good",recap:null}}};const x=await run({paths,existingArtifact:old,fetchImpl:async()=>({ok:false,status:400,json:async()=>({error:{code:"bad_request"}}),headers:{get:()=>null}})});assert.equal(x.summary.preserved,1);assert.equal(old.profiles["jane-doe"].bio,"Last known good");});
test("invalid informal copy is rejected",()=>{const p=enrichRoster(roster(),nfl(),directory)[0];const v=validateGeneratedProfile({bio:"Our receiver brings energy!",recap:null},p);assert.equal(v.valid,false);assert.match(v.errors.join(" "),/fan language/);});
test("injury commentary is rejected even when roster status contains injury context",()=>{const p=enrichRoster(roster([{id:"jane-doe",name:"Jane Doe",position:"WR",number:11,status:"Reserve/Injured"}]),nfl(),directory)[0];assert.equal(validateGeneratedProfile({bio:"Wide receiver Jane Doe is injured.",recap:null},p).valid,false);});
test("profiles without statistics require a null overview",()=>{const p=enrichRoster(roster(),nfl(),directory)[0];assert.equal(validateGeneratedProfile(validOutput(false),p).valid,true);assert.equal(validateGeneratedProfile({...validOutput(false),recap:{paragraph:"Generic",bullets:[]}},p).valid,false);});
test("semantic hash excludes fetch timestamps",()=>{const p=enrichRoster(roster(),nfl({updatedAt:"a"}),directory)[0],q=enrichRoster(roster(),nfl({updatedAt:"b"}),directory)[0];assert.equal(semanticInputHash(p,DEFAULT_MODEL),semanticInputHash(q,DEFAULT_MODEL));});
test("default prompt version is professional v2",()=>assert.equal(PROMPT_VERSION,"professional-player-profile-v2"));
test("production validator uses the shared all-current-status rule",()=>{const source=fs.readFileSync(path.resolve("scripts/validate-player-profiles.mjs"),"utf8");assert.match(source,/filter\(isCurrentRosterPlayer\)/);assert.doesNotMatch(source,/status\s*===\s*["']Active/);});
test("empty production artifact is rejected",()=>{const paths=tempPaths();fs.writeFileSync(paths.artifactPath,JSON.stringify({profiles:{}}));const result=spawnSync(process.execPath,["scripts/validate-player-profiles.mjs","--production"],{cwd:path.resolve("."),env:{...process.env,PLAYER_PROFILES_ARTIFACT:paths.artifactPath},encoding:"utf8"});assert.notEqual(result.status,0);assert.match(`${result.stdout}${result.stderr}`,/zero biographies/);});
