#!/usr/bin/env node
import {mkdir,open,readFile,rename,stat} from "node:fs/promises";
import {dirname,resolve,sep} from "node:path";
import {pathToFileURL} from "node:url";
import {reserveEventSpyAttempt} from "./eventspy-ledger.mjs";
import {MIRROR_EVENT,MIRROR_EVENT_ID,MIRROR_GAME_ID,MIRROR_MARKETS,MIRROR_SOURCE_URL,eventSpyMirrorCounts,safeMirrorProviderUrl,validateEventSpyMirror} from "../../src/lib/tickets/eventspy-mirror-schema.mjs";

const UA="SeahawksFanZone-EventSpyMirror/1.0 (+https://seahawksfanzone.com/about)";
const outcomes={collect:"EVENTSPY_MIRROR_COLLECTION_SUCCESS",validate:"EVENTSPY_MIRROR_FILE_OK",verify:"EVENTSPY_MIRROR_PAGE_OK"};
const err=(code,message)=>Object.assign(new Error(message),{code});
const boundedError=e=>({outcome:/^[A-Z][A-Z0-9_]{1,63}$/.test(e?.code)?e.code:"EVENTSPY_MIRROR_FAILED",error:String(e?.message||"Mirror operation failed.").replace(/[\r\n<>]/g," ").slice(0,180)});
const inside=(file,root)=>{const f=resolve(file),r=resolve(root);return f===r||f.startsWith(r+sep)};
export function parseMirrorArgs(argv){const [command,...rest]=argv;if(!["collect","validate-file","verify-page"].includes(command))throw err("EVENTSPY_COMMAND_INVALID","Unknown command.");const allowed=command==="collect"?["game","output","ledger-root"]:command==="validate-file"?["file"]:["url","snapshot","screenshot"],options={};for(let i=0;i<rest.length;i+=2){const key=rest[i]?.match(/^--([a-z-]+)$/)?.[1];if(!key||!allowed.includes(key)||Object.hasOwn(options,key)||i+1>=rest.length||rest[i+1].startsWith("--"))throw err("EVENTSPY_OPTIONS_INVALID","Invalid command options.");options[key]=rest[i+1]}if(Object.keys(options).length!==allowed.length)throw err("EVENTSPY_OPTIONS_INVALID","Required option omitted.");for(const key of ["output","ledger-root","file","snapshot","screenshot"])if(options[key]&&(!options[key].startsWith("/")||options[key].split("/").includes("..")))throw err("EVENTSPY_PATH_INVALID","Paths must be absolute and contained.");if(command==="collect"){if(options.game!==MIRROR_GAME_ID)throw err("EVENTSPY_GAME_INVALID","Only game 1392216 is authorized.");const outputRoot=dirname(options.output);if(!inside(options.output,outputRoot))throw err("EVENTSPY_PATH_INVALID","Unsafe path.");}if(command==="verify-page"){let u;try{u=new URL(options.url)}catch{throw err("EVENTSPY_URL_INVALID","Invalid verification URL.")}if(u.protocol!=="http:"||u.hostname!=="127.0.0.1"||u.port!=="4324"||u.pathname!=="/tickets/"||u.search!==`?game=${MIRROR_GAME_ID}`||u.hash)throw err("EVENTSPY_URL_INVALID","Verification URL is not authorized.");}return{command,options}}
const text=async locator=>(await locator.innerText()).replace(/\s+/g," ").trim();
const cents=value=>{const hit=String(value).match(/\$\s*([1-9]\d{0,5}(?:,\d{3})*)(?:\.(\d{2}))?/);if(!hit)throw err("EVENTSPY_SUMMARY_INVALID","Malformed visible price.");return Number(hit[1].replaceAll(",",""))*100+Number(hit[2]||0)};
const isoFromTooltip=value=>{const m=String(value).match(/(\d{1,2})\s+([A-Za-z]{3})\s+(\d{2,4}).*?(\d{1,2}):(\d{2})\s*(PST|PDT)/i);if(!m)throw err("EVENTSPY_TOOLTIP_INVALID","Invalid tooltip timestamp.");const months={jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11},year=Number(m[3])+(m[3].length===2?2000:0),utc=Date.UTC(year,months[m[2].toLowerCase()],Number(m[1]),Number(m[4])+(m[6].toUpperCase()==="PDT"?7:8),Number(m[5]));if(!Number.isFinite(utc)||utc>Date.now()+60_000)throw err("EVENTSPY_TOOLTIP_INVALID","Impossible tooltip timestamp.");return new Date(utc).toISOString()};
export function parseMirrorTooltip(raw,{now=Date.now()}={}){if(typeof raw!=="string"||raw.length>4096||/[<>]/.test(raw))throw err("EVENTSPY_TOOLTIP_INVALID","Invalid tooltip.");const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),observedAt=isoFromTooltip(lines[0]),point={observedAt};if(Date.parse(observedAt)>now+60_000)throw err("EVENTSPY_TOOLTIP_INVALID","Future tooltip.");const seen=new Set();for(let i=1;i<lines.length;i++){const key=MIRROR_MARKETS.find(m=>lines[i].replace(/\s/g,"").toLowerCase()===m);if(!key){if(/^(?:section|lowest ticket price|price history)\b/i.test(lines[i]))continue;throw err("EVENTSPY_TOOLTIP_INVALID","Unexpected tooltip label.")}if(seen.has(key))throw err("EVENTSPY_TOOLTIP_INVALID","Duplicate tooltip marketplace.");seen.add(key);const next=lines[++i];point[`${key}Cents`]=/^(?:n\/a|—|-|unavailable)$/i.test(next)?null:cents(next)}for(const m of MIRROR_MARKETS)point[`${m}Cents`]??=null;if(!seen.size)throw err("EVENTSPY_TOOLTIP_INVALID","Tooltip contains no prices.");return point}
const mergePoints=values=>{const map=new Map();for(const p of values){const old=map.get(p.observedAt)??{observedAt:p.observedAt,...Object.fromEntries(MIRROR_MARKETS.map(m=>[`${m}Cents`,null]))};for(const m of MIRROR_MARKETS){const k=`${m}Cents`;if(old[k]===null&&p[k]!==null)old[k]=p[k];else if(old[k]!==null&&p[k]!==null&&old[k]!==p[k])throw err("EVENTSPY_TOOLTIP_INVALID","Conflicting tooltip values.")}map.set(p.observedAt,old)}return [...map.values()].sort((a,b)=>Date.parse(a.observedAt)-Date.parse(b.observedAt))};
async function visibleTooltip(wrapper,now){const tip=wrapper.locator(".recharts-tooltip-wrapper:visible");if(await tip.count()!==1)return null;try{return parseMirrorTooltip(await tip.innerText(),{now})}catch{return null}}
export async function walkMirrorChart(chart,wrapper,{now=Date.now()}={}){const points=[];await chart.focus();let first=null,same=0;for(let i=0;i<500&&same<5;i++){await chart.press("ArrowLeft");const p=await visibleTooltip(wrapper,now);if(!p)continue;points.push(p);same=p.observedAt===first?same+1:0;first=p.observedAt}let last=null;same=0;for(let i=0;i<500&&same<5;i++){await chart.press("ArrowRight");const p=await visibleTooltip(wrapper,now);if(!p)continue;points.push(p);same=p.observedAt===last?same+1:0;last=p.observedAt}let merged=mergePoints(points);if(merged.length<2){const box=await chart.boundingBox();if(box)for(let i=0;i<=100;i++){await chart.page().mouse.move(box.x+(box.width*i/100),box.y+box.height/2);const p=await visibleTooltip(wrapper,now);if(p)points.push(p)}merged=mergePoints(points)}return merged}
async function card(page,label){const root=page.getByText(new RegExp(`^${label}$`,"i")).first().locator("xpath=ancestor::*[self::div or self::article][1]");return text(root)}
export async function extractMirrorPage(page,{now=Date.now()}={}){let escaped=false;page.on("framenavigated",f=>{if(f===page.mainFrame()&&f.url()!=="about:blank"&&f.url()!==MIRROR_SOURCE_URL)escaped=true});const response=await page.goto(MIRROR_SOURCE_URL,{waitUntil:"domcontentloaded",timeout:30000});const status=response?.status?.()??0;if(status<200||status>=400)throw err("EVENTSPY_HTTP_STATUS_REJECTED","Main document status rejected.");if(page.url()!==MIRROR_SOURCE_URL||escaped)throw err("EVENTSPY_UNAPPROVED_REDIRECT","Source redirected.");const body=(await page.locator("body").innerText()).slice(0,20000);if(/captcha|access denied|verify (?:you are|that you are) human|checking your browser|service unavailable/i.test(body))throw err("EVENTSPY_ACCESS_BLOCKED","Access or challenge page.");const heading=page.getByRole("heading",{name:/Seattle Seahawks\s+(?:vs\.?|v\.?|versus)\s+New England Patriots/i});if(await heading.count()!==1)throw err("EVENTSPY_HEADING_MISMATCH","Event heading mismatch.");if(!/Lumen Field/i.test(body)||!/Seattle,\s*WA/i.test(body))throw err("EVENTSPY_IDENTITY_MISMATCH","Venue or location mismatch.");if(!/(?:September|Sep\.?)\s+9(?:th)?,?\s+2026/i.test(body))throw err("EVENTSPY_DATE_MISMATCH","Event date mismatch.");
 const consent=page.getByRole("dialog").filter({hasText:/cookie|consent|privacy/i});if(await consent.count()){const button=consent.getByRole("button",{name:/^(?:accept(?: all)?|agree|continue|dismiss|close)$/i}).first();if(!await button.count())throw err("EVENTSPY_CONSENT_BLOCKED","Consent obstructs the page.");await button.click()}
 const thirty=page.getByRole("button",{name:/^30d$/i}).first();if(!await thirty.count())throw err("EVENTSPY_CHART_MISSING","30d control missing.");await thirty.click();await page.waitForTimeout(200);if((await thirty.getAttribute("aria-pressed"))==="false")throw err("EVENTSPY_CHART_MISSING","30d control did not activate.");const historyHeading=page.getByRole("heading",{name:/^Lowest Ticket Price History$/i}).first(),chart=historyHeading.locator("xpath=following::*[@role='application'][1]"),wrapper=chart.locator("xpath=ancestor::*[contains(concat(' ',normalize-space(@class),' '),' recharts-wrapper ')][1]");if(await chart.count()!==1||await wrapper.count()!==1)throw err("EVENTSPY_CHART_MISSING","History chart missing.");const history=await walkMirrorChart(chart,wrapper,{now});
 const providers={};const region=page.getByText(/^View Tickets$/i).first().locator("xpath=ancestor::*[self::section or self::div][1]");for(const market of MIRROR_MARKETS){const name={ticketmaster:"Ticketmaster",stubhub:"StubHub",vividseats:"VividSeats",seatgeek:"SeatGeek"}[market],links=region.getByRole("link",{name:new RegExp(name,"i")});if(await links.count()!==1)throw err("EVENTSPY_PROVIDER_INVALID",`Missing or duplicate ${name} link.`);const href=await links.first().getAttribute("href"),safe=safeMirrorProviderUrl(href);if(!safe)throw err("EVENTSPY_PROVIDER_INVALID",`Unsafe ${name} link.`);providers[market]=safe}
 const currentRaw=await card(page,"Current Lowest"),sevenRaw=await card(page,"7-Day Lowest"),daysRaw=await card(page,"Days Until Event"),current=cents(currentRaw),seven=cents(sevenRaw);const age=s=>s.match(/(?:updated|ago|observed)[^\n]{0,80}/i)?.[0]||"Source observation";const latest=history.at(-1),winners=latest?MIRROR_MARKETS.filter(m=>latest[`${m}Cents`]===current):[],timeLabel=body.match(/\b\d{1,2}:\d{2}\s*(?:AM|PM)\s*PDT\b/i)?.[0].replace(/\s+/g,"");if(!timeLabel)throw err("EVENTSPY_IDENTITY_MISMATCH","Local event time missing.");const sevenPoint=[...history].reverse().find(p=>MIRROR_MARKETS.some(m=>p[`${m}Cents`]===seven));
 return validateEventSpyMirror({schemaVersion:"1.0.0",source:"eventspy",currency:"USD",gameId:MIRROR_GAME_ID,sourceEventId:MIRROR_EVENT_ID,sourceUrl:MIRROR_SOURCE_URL,trackingUrl:MIRROR_SOURCE_URL,collectedAt:new Date(now).toISOString(),event:{...MIRROR_EVENT,localTimeLabel:timeLabel},summary:{daysUntilEvent:Number(daysRaw.match(/\b\d+\b/)?.[0]),currentLowestCents:current,currentLowestMarketplace:winners.length===1?winners[0]:null,currentLowestObservedAt:latest.observedAt,currentLowestAgeLabel:age(currentRaw),sevenDayLowestCents:seven,sevenDayLowestObservedAt:sevenPoint?.observedAt||latest.observedAt,sevenDayLowestAgeLabel:age(sevenRaw),atSevenDayLow:/at (?:the )?7-day low/i.test(currentRaw+" "+sevenRaw)},providerLinks:providers,history},{now});}
export async function atomicPublish(file,value){validateEventSpyMirror(value);await mkdir(dirname(file),{recursive:true});const temp=`${file}.tmp-${process.pid}`;let handle;try{handle=await open(temp,"wx",0o644);await handle.writeFile(`${JSON.stringify(value)}\n`);await handle.sync();await handle.close();handle=null;await rename(temp,file);try{const dir=await open(dirname(file),"r");await dir.sync();await dir.close()}catch{}}finally{await handle?.close().catch(()=>{})}}
async function loadSnapshot(file){return validateEventSpyMirror(JSON.parse(await readFile(file,"utf8")))}
async function chromium(){return(await import("playwright-core")).chromium}
export async function collect(options,deps={}){const reserve=deps.reserve??reserveEventSpyAttempt,reservation=await reserve(options["ledger-root"],MIRROR_GAME_ID,Date.now());if(!reservation.allowed)throw err("EVENTSPY_DAILY_LIMIT","Daily navigation limit reached.");const engine=deps.chromium??await chromium();let browser,context,page;try{browser=await engine.launch({headless:true});context=await browser.newContext({userAgent:UA,storageState:undefined,acceptDownloads:false});page=await context.newPage();const snapshot=await extractMirrorPage(page);await atomicPublish(options.output,snapshot);return{outcome:outcomes.collect,...eventSpyMirrorCounts(snapshot)}}finally{await page?.close().catch(()=>{});await context?.close().catch(()=>{});await browser?.close().catch(()=>{})}}
export async function verify(options,deps={}){const snapshot=await loadSnapshot(options.snapshot),engine=deps.chromium??await chromium();let browser,context,page;try{browser=await engine.launch({headless:true});context=await browser.newContext({viewport:{width:1147,height:786}});page=await context.newPage();const errors=[];page.on("pageerror",e=>errors.push(e));await page.goto(options.url,{waitUntil:"networkidle"});const root=page.locator("#eventspy-mirror[data-eventspy-mirror-ready='true']");if(await root.count()!==1||errors.length)throw err("EVENTSPY_MIRROR_PAGE_MISMATCH","Rendered mirror is not ready.");for(const [attr,value] of [["data-game-id",snapshot.gameId],["data-history-points",String(snapshot.history.length)],["data-provider-links","4"],["data-current-lowest-cents",String(snapshot.summary.currentLowestCents)],["data-seven-day-lowest-cents",String(snapshot.summary.sevenDayLowestCents)]])if(await root.getAttribute(attr)!==value)throw err("EVENTSPY_MIRROR_PAGE_MISMATCH",`DOM mismatch: ${attr}.`);for(const market of MIRROR_MARKETS)if(await page.locator(`[data-provider="${market}"]`).getAttribute("href")!==snapshot.providerLinks[market])throw err("EVENTSPY_MIRROR_PAGE_MISMATCH",`Provider mismatch: ${market}.`);for(const selector of ["[data-history-chart]","[data-range='30']","[data-range='14']","[data-range='7']","[data-show-filters]","[data-market-selector]"])if(!await page.locator(selector).isVisible())throw err("EVENTSPY_MIRROR_PAGE_MISMATCH",`Missing ${selector}.`);await mkdir(dirname(options.screenshot),{recursive:true});await page.screenshot({path:options.screenshot,fullPage:true});if((await stat(options.screenshot)).size<1000)throw err("EVENTSPY_MIRROR_PAGE_MISMATCH","Screenshot is empty.");return{outcome:outcomes.verify,...eventSpyMirrorCounts(snapshot)}}finally{await page?.close().catch(()=>{});await context?.close().catch(()=>{});await browser?.close().catch(()=>{})}}
export async function run(argv){const {command,options}=parseMirrorArgs(argv);if(command==="collect")return collect(options);if(command==="validate-file"){const snapshot=await loadSnapshot(options.file);return{outcome:outcomes.validate,...eventSpyMirrorCounts(snapshot)}}return verify(options)}
if(import.meta.url===pathToFileURL(process.argv[1]||"").href){try{console.log(JSON.stringify(await run(process.argv.slice(2))))}catch(e){console.log(JSON.stringify(boundedError(e)));process.exitCode=e?.code==="EVENTSPY_DAILY_LIMIT"?4:1}}
